development:
  omniauth_provider_key: Bugyug4atFvQ4yGfgUwad59M0
  omniauth_provider_secret: GZaksRtt6W8rNXq6hx6VINXIoMZu7Plp3j6cz5XvTF768FU3ay
  khan_provider_key: RQEpWqc57wDChN8J
  khan_provider_secret: 7DNy53BLP4HYU6Ph

  domain_name: example.com
  secret_key_base: 23dc9fb70639c852847baa032ce3e79ddac516ca0c856ecf31f02167b951f416f8342e6404454696092a15727e2e9556bc9da7689411f17f0a351e8fd9b549ef

test:
  secret_key_base: a2cb2cdcc17095a15c07884eefe981f487cc82f2f985c3c80dff859bb2319de352aba526c63e253061c8c2376deedf7abf8998e2f0b913e5a03d986cdea27125

production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
